---
# Playbook to deploy the entire picoCTF environment

- hosts: shell
  become: yes
  become_method: sudo
  roles:
    - {role: common     , tags: ["common"]}
    - {role: pico-docker, tags: ["pico-docker"]}
    - {role: pico-shell , tags: ["pico-shell"]}

- hosts: web
  become: yes
  become_method: sudo
  pre_tasks:
    - import_role:
        name: pico-docker
        tasks_from: config_user
      vars:
        client: "{{web_hostname}}"
  roles:
    - {role: common     , tags: ["common"]}
    - {role: mongodb    , tags: ["db"]}
    - {role: pico-web   , tags: ["pico-web"]}
