---
# Playbook to deploy the entire picoCTF environment

- hosts: shell
  become: yes
  become_method: sudo
  pre_tasks:
    - import_tasks: "../ansible/tasks/vagrant_shell_bootstrap.yml"
  roles:
    - {role: common     , tags: ["common"]}
    - {role: pico-docker, tags: ["pico-docker"], when: enable_docker}
    - {role: pico-shell , tags: ["pico-shell"]}

- hosts: web
  become: yes
  become_method: sudo
  pre_tasks:
    - import_tasks: "../ansible/tasks/vagrant_web_bootstrap.yml"
  roles:
    - {role: common     , tags: ["common"]}
    - {role: mongodb    , tags: ["db"]}
    - {role: pico-web   , tags: ["pico-web"]}
