---
# Variables shared across all remote_testing hosts

# admin is the default user for the AWS Debian Jessie AMI
ansible_user: admin

# Enviromentmantal specific web settings
web_fqdn: "staging.picoctf.com"
nginx_server_name: "{{ web_fqdn }}"
flask_app_server_name: "{{ web_fqdn }}"
web_address: "http://203.0.113.254"
web_address_internal: "http://10.0.1.10"
enable_basic_auth: true
htpasswd_accounts: "{{ vault_htpasswd_accounts }}"

# Enviromentmantal specific shell settings
shell_hostname: "203.0.113.254"
shell_admin_password_crypt: "{{ vault_shell_admin_password_crypt }}"
shell_manager_deploy_secret: " {{ vault_shell_manager_deploy_secret }}"

# Enviromentmantal specific database settings
db_private_ip: 10.0.1.20
picoAdmin_db_password: "{{ vault_picoAdmin_db_password}}"
picoWeb_db_password: "{{vault_picoWeb_db_password }}"
env_db_users:
  - {
    name: picoWeb,
    password: "{{ picoWeb_db_password }}",
    roles: readWrite,
    database: "{{ picoCTF_db_name }}"
  }
