os: linux
dist: xenial
sudo: false

language: python
cache: pip

# turn off notifications
notifications:
  email: false


before_script:
  - pip install tox

# test script
script:  tox

matrix:
  include:
    - python: 3.7
      env: TOXENV=flake8
  allow_failures:
    - env: TOXENV=flake8
