---
# Playbook that runs tasks common across all servers

- include: upgrade.yml
  tags:
    - network
    - dependency

- include: utils.yml
  tags:
    - network
    - dependency

# Developement settings are the only environment where the platform should
# be loaded in directly without being cloned from a specific source and
# branch
- include_vars: group_vars/common.yml
- include: clone_repo.yml
  when: "'local_development' not in group_names"
  tags:
    - network
