---
# Playbook that runs tasks common across all servers

- include: upgrade.yml
  tags:
    - network
    - dependency

- include: utils.yml
  tags:
    - network
    - dependency

# Local development environements are the only place the platform should
# be loaded in directly without being cloned from a specific source and branch
- include: clone_repo.yml
  when: "'env_local_development' not in group_names"
  tags:
    - network
