---
# Playbook that installs base utilities we would want on any server

- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install base packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - curl
    - vim
    - tmux
    - git
    - python-passlib    # required for htpasswd module
    - aptitude          # required for apt module
