---
# Playbook to deploy the entire picoCTF environment

- hosts: shell
  become: yes
  become_method: sudo
  pre_tasks:
    # allow the web to SSH to the shell server to load deployment
    # key created and fetched in 00_bootstrap.yml
    - import_tasks: "../ansible/tasks/util_admin_user.yml"
      vars:
        admin: "{{ ansible_user }}"
        keys: ["./keys/web_id_rsa.pub"]
  roles:
    - {role: common     , tags: ["common"]}
    - {role: pico-docker, tags: ["pico-docker"]}
    - {role: certbot    , tags: ["certbot"]}
    - {role: pico-shell , tags: ["pico-shell"]}

- hosts: web
  become: yes
  become_method: sudo
  pre_tasks:
    - import_role:
        name: pico-docker
        tasks_from: config_user
      vars:
        client: "{{web_hostname}}"
  roles:
    - {role: common     , tags: ["common"]}
    - {role: mongodb    , tags: ["db"]}
    - {role: certbot    , tags: ["certbot"]}
    - {role: pico-web   , tags: ["pico-web"]}
