---
# Defaults for the picoCTF-web role. These are the loweset priority variables
# and can easily be overridden in group_vars, host_vars, or the command line.

##
# Problem Settings
# These will only be used if `problem_source_dirs` and `bundles` are not 
# specified in an environmental configuration AND `auto_load_problems` is True
##
problem_source_dirs:
  - "{{ pico_base_dir }}/problems/examples"

bundles:
  - {
    source: "{{ pico_base_dir }}/problems/bundles/challenge-sampler.json",
    name: "challenge-sampler",
    instances: 2
  }
  - {
    source: "{{ pico_base_dir }}/problems/bundles/challenge-sampler-tools.json",
    name: "challenge-sampler-tools",
    instances: 1
  }
