---
# Variables shared across all database deloyments

# These are variables you are most likely to consider changing or overloading
# in an environemental specific group_vars file.  Addtional varaibles that can
# be overloaded are contained in roles/mongodb/defaults/main.yml

picoCTF_db_name: picoCTF3
db_data_path: "/data"

# MongoDB User Variables (used in configure_auth.yml task)
# Passwords should be stored outside version control or in an 
# ansible-vault protected file.
initial_admin_name: picoAdmin
initial_admin_password: "{{ picoAdmin_db_password }}"

# Add additional users an environement specific group_vars file
mongodb_users: "{{ env_db_users }}"
