---
# Variables shared across all staging playbooks
ansible_user: vagrant
ansible_ssh_pass: vagrant


# picoCTF-web and picoCTF-shell variables
pico_repo: "https://github.com/picoCTF/picoCTF-platform"
pico_verison: "master"
pico_code_dir: "/vagrant2"
pico_http_dir: "/srv/http/ctf"

## nginx
pico_server_name: "{{ web_fqdn }}"
pico_http_alias: "{{ pico_http_dir }}/$1.html"
pico_api_proxy_pass: "http://127.0.0.1:8000"
pico_api_auth_user:  "/api/user/authorize/user"
pico_api_auth_teacher: "/api/user/authorize/teacher"
pico_api_auth_admin: "/api/user/authorize/admin"
pico_site_config_name: "ctf"

pico_internal_allow: "10.0.1.0/24"
pico_game_redirect: "http://game.staging.picoctf.com"

pico_web_api_dir: "{{ web_code_dir }}"

# picoCTF-webapp
web_fqdn: "staging.picoctf.com"
web_repo:  "https://github.com/royragsdale/picoCTF-web"
web_verison: "staging"
web_code_dir:  "/picoCTF-web"
web_config_dir:  "/picoCTF-web-config"

pico_web_js_out_path: "{{ pico_web_api_dir}}/web/js/"
pico_web_coffescript_in_path: "{{ pico_web_api_dir}}/web/coffee/"

pico_web_backup_dir: "/backup"

