---
# Variables shared across all shell server deloyments

# Should not need to change this file. Environmental specific configurations
# should be made in the group specific variables file, eg: local.yml or remote_testing.yml

# pico_base_dir set in common.yml
pico_shell_manager_dir:  "{{pico_base_dir}}/picoCTF-shell"

###
# Shellinabox configuration
###
shellinabox_js_path: "/opt/hacksports/shellinabox/ShellInABox.js"

# configure nginx
shell_site_config_name: "shell"
shellinaboxd_port: "4242"
shellinabox_server_path: "http://127.0.0.1:{{ shellinaboxd_port }}/"

# problem settings
deb_dir:    "/picoCTF-debs"
bundle_dir: "/picoCTF-bundles"
