---
# Variables shared across all staging playbooks
ansible_user: admin

# Defined in Terrafrom (temporarily static)
db_data_device: "/dev/xvdf"
db_data_device_fstype: "ext4"
db_data_path: "/data"
db_data_mount_opts: "defaults,auto,noatime,noexec 0 0"

# Static from Terraform
db_private_ip: 10.0.1.20

# MongoDB Configuration Variables (used in configure_mongo.yml task)
mongodb_user: mongodb
mongodb_daemon_name: mongod

mongodb_apt_keyserver: keyserver.ubuntu.com
mongodb_apt_key_id: EA312927
mongodb_repo: 'deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.2 main'

mongodb_conf_auth: true                           # Run with security
mongodb_conf_bind_ip: "0.0.0.0"                   # IP addresses to listen on (Static)
mongodb_conf_dbpath: "{{ db_data_path }}"         # Directory for datafiles (Static)
mongodb_conf_nohttpinterface: true                # Disable http interface
mongodb_conf_journal: true                        # Enable journaling
mongodb_conf_logappend: true                      # Append to logpath instead of over-writing
mongodb_conf_logpath: /var/log/mongodb/{{ mongodb_daemon_name }}.log # Log file to send write to instead of stdout
mongodb_conf_port: 27017                          # Specify port number

# MongoDB User Variables (used in configure_auth.yml task)
# Passwords are stored outside version control
initial_admin_name: picoAdmin
initial_admin_password: "{{ picoAdmin_db_password }}"

mongodb_root_admin_name: rootAdmin
mongodb_root_admin_password: "{{ root_db_password }}"

picoCTF_db_name: picoCTF3

# Add additional users here
mongodb_users:
  - {
    name: picoWeb,
    password: "{{ picoWeb_db_password }}",
    roles: readWrite,
    database: "{{ picoCTF_db_name }}"
  }
  - {
    name: cocoWeb,
    password: "{{ cocoWeb_db_password }}",
    roles: readWrite,
    database: "{{ picoCTF_db_name }}"
  }
  - {
    name: cocoAdmin,
    password: "{{ cocoAdmin_db_password }}",
    roles: "userAdminAnyDatabase,readWriteAnyDatabase",
    database: "admin"
  }

# picoCTF-web variables
pico_repo: "https://github.com/picoCTF/picoCTF-platform"
pico_code_dir: "/vagrant"
pico_http_dir: "/srv/http/ctf"

## nginx
pico_server_name: "_"                                 # catch all [TODO]
pico_http_alias: "{{ pico_http_dir }}/$1.html"
pico_api_proxy_pass: "http://localhost:8000"
pico_api_auth_user:  "/api/user/authorize/user"
pico_api_auth_teacher: "/api/user/authorize/teacher"
pico_api_auth_admin: "/api/user/authorize/admin"
pico_site_config_name: "ctf"

pico_web_api_dir: "{{ pico_code_dir }}/picoCTF-web"

pico_web_install_command: "{{pico_code_dir}}/scripts/web_setup.sh"
