---
# Variables shared across all web server deloyments

# Should not need to change this file. Environmental specific configurations
# should be made in the group specific variables file, ex: local.yml or staging.yml

web_code_dir:  "/picoCTF/picoCTF-web"

###
# picoCTF-web and API configuration
###
web_config_dir:  "/picoCTF-web-config"
pico_web_api_dir: "{{ web_code_dir }}"
pico_web_js_out_path: "{{ pico_web_api_dir}}/web/js/"
pico_web_coffescript_in_path: "{{ pico_web_api_dir}}/web/coffee/"
pico_web_backup_dir: "/backup"

###
# Nginx configuration
###
pico_server_name: "{{ web_fqdn }}"
pico_http_dir: "/srv/http/ctf"
pico_http_alias: "{{ pico_http_dir }}/$1.html"
pico_api_proxy_pass: "http://127.0.0.1:8000"
pico_api_auth_user:  "/api/user/authorize/user"
pico_api_auth_teacher: "/api/user/authorize/teacher"
pico_api_auth_admin: "/api/user/authorize/admin"
pico_site_config_name: "ctf"

# http access and staging specific
# [todo] factor out
pico_internal_allow: "10.0.1.0/24"
pico_game_redirect: "http://game.staging.picoctf.com"

###
# Gunicorn configuration
##

gunicorn_user: "{{ ansible_user }}"
gunicorn_group: "{{ ansible_user }}"
gunicorn_working_dir: "{{ pico_web_api_dir }}"
gunicorn_listen_on: "127.0.0.1:8000"
num_workers: 2
