---
# Playbook that installs the dependencies for the picoctf-web server

- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

# Extracted from picoCTF-platform/scripts/web_setup.sh
- name: Install picoCTF platform system dependencies
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - python3-pip
    - gunicorn
    - jekyll 
    - nginx
