---
# Playbook that installs and configures picoCTF-web servers

- include_vars:  group_vars/common.yml
  tags:
    - always

# Need to load passwords from the vault for staging environments
- include_vars: group_vars/vault_staging.yml
  when: "'staging' in group_names"

- include: dependencies.yml
  tags:
    - network
    - dependency

- include: nodejs.yml
  tags:
    - network
    - dependency

- include: nginx.yml
- include: picoCTF-webapp.yml
- include: gunicorn.yml
#- include: monit.yml

- name: Ensure nginx is running
  service: 
    name: nginx
    state: started
    enabled: yes
