---
# Playbook that installs and configures picoCTF-web servers

- include_vars:  group_vars/common.yml
  tags:
    - always

# Need to load passwords from the vault for remote environments
- include_vars: group_vars/vault_remote_testing.yml
  when: "'env_remote_testing' in group_names"

- include: dependencies.yml
  tags:
    - network
    - dependency

- include: nodejs.yml
  tags:
    - network
    - dependency

- include: nginx.yml
- include: picoCTF-webapp.yml
- include: gunicorn.yml

- name: Ensure nginx is running
  service: 
    name: nginx
    state: started
    enabled: yes

# Adds a shell server then loads problems and bundles from it.
- name: Autoload Shell Server into web interface
  script: >
    scripts/add_shell_server.py
    "{{ shell_name }}"
    {{ shell_host }}
    {{ shell_user }}
    {{ shell_pass }}
    {{ shell_port }}
    {{ shell_prot }}
  environment:
    APP_SETTINGS_FILE: "{{ web_config_dir }}/deploy_settings.py"
  when: auto_add_shell
  register: command_result
  changed_when: "command_result.stdout_lines[0] == 'Loaded problems and bundles successfully'"
  no_log: True
