---
# Playbook that installs and configures nginx
# This is the base  picoCTF web nginx configuration

- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure nginx is installed
  apt:
    pkg: nginx
    state: present

- name: Add picoCTF site configuration to nginx
  template: 
    src: ctf.nginx.j2
    dest: "/etc/nginx/sites-available/{{ pico_site_config_name }}"
    backup: yes
    owner: root
    group: root
    mode: 0644

# HTTP Basic Auth used to secure the staging competition site
- name: Setup HTTP basic auth
  htpasswd:
    path: "/etc/nginx/.htpasswd"
    name: "{{ item.user }}"
    password: "{{ item.password }}"
    owner: root
    group: root
    mode: 0640
  no_log: True
  with_items: "{{ htpasswd_accounts }}"

- name: Enable picoCTF site configuration
  file:
    src: "/etc/nginx/sites-available/{{ pico_site_config_name }}"
    dest: "/etc/nginx/sites-enabled/{{ pico_site_config_name }}"
    owner: root
    group: root
    state: link
  notify :
    - nginx restart

- name: Disable default nginx site configuration
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
