---
# Defaults for the picoCTF-web role. These are the loweset prioirty varaibles
# and can easily be overridden in group_vars, host_vars, or command line

# Auto Configuration flags
auto_add_shell: False
auto_load_problems: False

# Default Shell Server
shell_name: ""
shell_host: ""
shell_user: ""
shell_pass: ""
shell_port: "22"
shell_proto: "HTTP"

# HTTP Basic Auth
enable_basic_auth: false
htpasswd_accounts: []
