---
# Playbook that assigns all the necessary roles to provision the backend database
- hosts: db
  remote_user: "{{ ansible_user }}"

  become: yes
  become_method: sudo

  roles:
    - common
    - mongodb
