---
# Playbook to deploy the entire picoCTF environment

- hosts: docker
  remote_user: "{{ ansible_user }}"
  become: yes
  become_method: sudo
  roles:
    - {role: common     , tags: ["common"]}
    - {role: docker     , tags: ["docker"]}
    - {role: docker_tls , tags: ["docker"], vars: {server_SAN: "{{docker_server_SAN}}"}}
  post_tasks:
    - import_tasks: "tasks/docker_gen_client_certs.yml"
    - import_tasks: "tasks/docker_prune_containers.yml"

- hosts: shell
  remote_user: "{{ ansible_user }}"
  become: yes
  become_method: sudo
  pre_tasks:
    - import_tasks: "tasks/docker_deploy_client_certs.yml"
  roles:
    - {role: common     , tags: ["common"]}
    - {role: pico-shell , tags: ["shell"]}

- hosts: db
  remote_user: "{{ ansible_user }}"
  become: yes
  become_method: sudo
  roles:
    - {role: common     , tags: ["common"]}
    - {role: mongodb    , tags: ["db"]}

- hosts: web
  remote_user: "{{ ansible_user }}"
  become: yes
  become_method: sudo
  pre_tasks:
    - import_tasks: "tasks/docker_deploy_client_certs.yml"
  roles:
    - {role: common     , tags: ["common"]}
    - {role: pico-web   , tags: ["web"]}
