---
# Playbook that assigns all the necessary roles to provision the web server
- hosts: web
  remote_user: "{{ ansible_user }}"
  become: yes
  become_method: sudo
  vars_files:
    - group_vars/db.yml 
  roles:
    - common
    - pico-web 
