---
# Playbook that installs and configures picoCTF-shell servers

# Needed so picoCTF-web can log in to get deployment information
- name: Set password for admin user
  user:
    name: "{{ ansible_user }}"
    password: "{{ shell_admin_password_crypt }}"
  no_log: True

- include: dependencies.yml

- include: shell_manager.yml

- include_role:
    name: nginx

- include: pam_and_services.yml

- include: deploy_problems.yml

- include: permissions.yml

- name: Hidepid
  command: mount -o remount,hidepid=2 /proc

- name: Hidepid persistence
  command: echo "proc   /proc   proc  defaults,hidepid=2  0   0"  >> /etc/fstab

- name: Copy over 99-motd
  copy:
    src: 99-motd
    dest: /etc/update-motd.d/99-motd
    owner: root
    group: root
    mode: 0755

- name: Disable inter-user messages by default
  lineinfile:
    path: /etc/profile
    line: mesg n

- name: Remove /var/log/wtmp
  file:
    path: /var/log/wtmp
    state: absent

- name: Restrict /var/run/utmp
  file:
    path: /var/run/utmp
    mode: go-r
