---
# Playbook that installs the dependencies for the picoctf-shell server

- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

# Extracted from picoCTF-platform/scripts/shell_setup.sh
# [TODO] document need (why)
# factored out to own 
# nginx, shellinabox
- name: Install picoCTF-shell system dependencies
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - software-properties-common
    - dpkg
    - dpkg-dev
    - fakeroot
    - python3
    - python3-pip
    - socat
    - php5-cli
    - gcc-multilib

# [TODO] check if these are relevant for challene templates, or what?
# document need
- name: Install uwsgi and plugins for shell server
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - uwsgi
    - uwsgi-plugin-php
    - uwsgi-plugin-python3
    - uwsgi-plugin-python
    - python-flask

# [TODO] factor out
- name: Install shellinabox from .deb
  apt:
    deb: "{{ shellinabox_deb_path }}"

# [TODO] factor out
- name: Install pam dependencies
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - libpam-python
    - python-setuptools
