---
# Playbook that installs the dependencies for the picoctf-shell server

- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 3600

# Extracted from picoCTF-platform/scripts/shell_setup.sh
- name: Install picoCTF-shell system dependencies
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - software-properties-common
    - dpkg
    - dpkg-dev
    - fakeroot
    - python-pip      # used for pam module dependencies
    - python3         # used by shell_manager
    - python3-pip     # used for shell_manager dependencies
    - libffi-dev
    - libssl-dev
    - socat
    - php5-cli
    - gcc-multilib
    - nginx           # used to serve shellinabox and challenge binaries
    - shellinabox


# Needed by templated challenge types
- name: Install uwsgi and plugins for shell server
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - uwsgi
    - uwsgi-plugin-php
    - uwsgi-plugin-python3
    - uwsgi-plugin-python
    - python-flask

- name: Install pam dependencies
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - libpam-python
    - python-setuptools

# needed for pam module
- name: Install requests
  pip:
    name: requests

- name: Install python packaging
  pip:
    name: packaging
    executable: pip3

- name: Install python appdirs
  pip:
    name: appdirs
    executable: pip3
