---
# Playbook to deploy problems on the shell server

- name: Ensure deb and bundle directories exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ deb_dir }}"
    - "{{ bundle_dir }}"

- name: Install problems
  command: "{{ virtualenv_dir }}/bin/shell_manager install {{ item }}"
  with_items: "{{ problem_source_dirs }}"

- name: Deploy problems
  command: "{{ virtualenv_dir }}/bin/shell_manager deploy -n 2 all"

- name: Install bundles
  command: "{{ virtualenv_dir }}/bin/shell_manager install-bundle {{ item }}"
  with_items: "{{ bundles }}"

- name: Install any missing dependencies
  apt:
    upgrade: full
    force: yes

- name: Change /tmp permission
  become: true
  file:
    path: /tmp
    mode: 01773

- name: Change /etc/xinetd.d permission
  become: true
  file:
    path: /etc/xinetd.d
    mode: 0750

# generally a good idea (on remote, we will find dist.bundle)
- name: Exclude group and others from ansible_user home directory
  file:
    path: "/home/{{ansible_user}}"
    mode: "g=,o="

# prevent user listing (some of the users are created for CTF problems)
- name: Mark /home as not world-readable
  file:
    path: "/home"
    mode: "o-r"

# usually this directory contains a .git (applicable to both local or remote)
- name: Exclude group and others from pico_base_dir
  file:
    path: "{{ pico_base_dir }}"
    mode: 0700
