---
# Playbook that installs and configures picoCTF-shell servers

# needed for: shell_admin_password_crypt
#- include_vars: secret_vars/staging_secret.yml

# Don't recurse, clone shell-manager seperately
# [TODO] - fix should not be nessecary shellinbox related
- name: Clone picoCTF-platform
  git: 
    repo: "{{ pico_repo }}" 
    version: "{{ pico_verison }}"
    dest: "{{ pico_code_dir }}"

- name: Clone picoCTF-shell-manager
  git: 
    repo: "{{ shell_manager_repo }}"
    version: "{{ shell_manager_verison }}"
    dest: "{{  pico_shell_manager_dir }}"

- name: Ensure admin user owns picoCTF-platform dir
  file:
    path: "{{ pico_code_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    recurse: yes

- name: Ensure admin user owns picoCTF-shell-manager dir
  file:
    path: "{{ pico_shell_manager_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    recurse: yes

    #- name: Ensure admin user owns pico http dir
    #file:
      #path: "{{ pico_http_dir }}"
      #owner: "{{ ansible_user }}"
      #group: "{{ ansible_user }}"
      #state: directory

# Needed so picoCTF-web can log in to get deployment information
- name: Set password for admin user
  user:
    name: "{{ ansible_user }}"
    password: "{{ shell_admin_password_crypt }}"

- include: dependencies.yml
- include: shell_manager.yml
- include: nginx.yml
- include: pam_and_services.yml
- include: deploy_private_problems.yml
  tags:
    - slow

- name: Ensure nginx is running
  service: 
    name: nginx
    state: started
    enabled: yes
    
    
# Missing
# monit
# journald
# any services
  # sudo systemctl add-wants default.target shell_manager.target 
# any hardening
#pip2 install requests 
# mkdir /tmp/hacksports/ 
# sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) universe"
# hostname setting

#chmod -R 1710 /var/cache/apt
#chmod 1710 /etc/apt/sources.list 
