---
# Playbook that installs and configures picoCTF-shell servers

- include_vars:  group_vars/common.yml
  tags:
    - always

# Need to load passwords from the vault for remote environments
- include_vars: group_vars/vault_remote_testing.yml
  when: "'env_remote_testing' in group_names" 

# Needed so picoCTF-web can log in to get deployment information
- name: Set password for admin user
  user:
    name: "{{ ansible_user }}"
    password: "{{ shell_admin_password_crypt }}"
  no_log: True

- include: dependencies.yml
  tags:
    - network
    - dependency

- include: shell_manager.yml
- include: nginx.yml
- include: pam_and_services.yml
- include: deploy_problems.yml

# [TODO] - refactor
- name: Ensure nginx is running
  service: 
    name: nginx
    state: started
    enabled: yes
    
    
# Missing
# journald
# services
#   sudo systemctl add-wants default.target shell_manager.target 
# hardening

