---
# Playbook to handle convenience preconfigurations so an admin is not
# required to set things up in the web ui by hand.

- include: auto_add_web_user.yml
  vars:
    web_user  : "{{ web_admin }}"
    web_pw    : "{{ web_admin_pw }}"
    web_email : "{{ admin_email }}"
  when: auto_add_web_admin
  tags: ["XXX"]

- name: Autoload Shell Server into web interface
  script: >
    add_shell_server.py
    {{ shell_name }}
    {{ shell_host }}
    {{ shell_user }}
    {{ shell_pass }}
    {{ shell_port }}
    {{ shell_proto }}
  register: add_shell_server_output
  environment:
    APP_SETTINGS_FILE: "{{ web_config_dir }}/deploy_settings.py"
    PATH: "{{ virtualenv_dir }}/bin/"
  args:
    executable: "{{ virtualenv_dir }}/bin/python"
  when: auto_add_shell

- name: Autoload Problems into web interface
  script: load_problems.py {{ add_shell_server_output.stdout }}
  environment:
    APP_SETTINGS_FILE: "{{ web_config_dir }}/deploy_settings.py"
    PATH: "{{ virtualenv_dir }}/bin/"
  args:
    executable: "{{ virtualenv_dir }}/bin/python"
  when: auto_load_problems

- name: Auto Start competition
  script: start_competition.py
  environment:
    APP_SETTINGS_FILE: "{{ web_config_dir }}/deploy_settings.py"
    PATH: "{{ virtualenv_dir }}/bin/"
  args:
    executable: "{{ virtualenv_dir }}/bin/python"
  when: auto_start_competition
