---
# Playbook that installs and configures picoCTF-web servers

- include: dependencies.yml

- include: nodejs.yml

- include_role:
    name: nginx

- include: picoCTF-webapp.yml

- include: gunicorn.yml

- include: daemons.yml

- include: auto_configure.yml
